### ISSUE TITLE
v4 compatibility

### ISSUE THREAD

**Issue by tdombos** [nishad/omeka-s-wikidata#7]
Please make the module compatible with Omeka S v4.0

**Comment by jrcwiok** [comment]
I use Omeka S for a graduate class in Museum Information Management at Pratt. The Wikidata plugin is one of our fave vocabularies to work with. Please make it compatible with ^4

**Comment by mariangiglio** [comment]
Is there any news about it? This would be incredibly useful for many projects

**Comment by cutterkom** [comment]
I would also like to use the Plugin with Omeka S > v.4

What changes need to be made?

**Comment by nishad** [comment]
The issue has been resolved with [PR#9](https://github.com/nishad/omeka-s-wikidata/pull/9) by @juanfuc, and the fix is included in the latest release, [v1.4.1](https://github.com/nishad/omeka-s-wikidata/releases/tag/v1.4.1). This update ensures the module now works with Omeka S 4.x versions.

  

The official module page ([https://omeka.org/s/modules/Wikidata/](https://omeka.org/s/modules/Wikidata/)) will be updated automatically within a day
